---
version: "3.7"

services:
  redis-context:
    image: redis:alpine
    container_name: redis-context
    expose:
      - 6379
    ports:
      - 6378:6379
    logging:
      driver: "none"
  mongo-context:
    build: ./mongo
    container_name: mongo-context
    expose:
      - 27017
    ports:
      - 27018:27017
    logging:
      driver: "none"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: database
    volumes:
      - ./mongo/data/db:/data/db
  context:
    build: ./
    container_name: context
    expose:
      - 4001
    ports:
      - 4001:4001
      - 49542:49542 #For debugging
    environment:
      NODE_ENV: development
      WAIT_HOSTS: mongo-context:27017
      WAIT_HOSTS_TIMEOUT: 60
      NODE_DEBUG: bull
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo-context
    entrypoint:
      - "/bin/sh"
      - -ecx
      - |
        /wait && yarn run dev

networks:
  default:
    external:
      name: teleport